//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    public partial class TheaterCityHallDetails
    {
        protected global::System.Web.UI.WebControls.FormView FormViewTheater;
        protected global::System.Web.UI.WebControls.GridView GridViewTheater;
        protected global::System.Web.UI.WebControls.FormView FormViewHall;
        protected global::System.Web.UI.WebControls.GridView GridViewHall;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceTheater;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceHall;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceTheaterDropdown;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceHallView;
    }
}
